/**
 * Todos los textos visibles del sitio y del panel Admin.
 *
 * Para cambiar un texto, editalo acá; no hace falta tocar los componentes.
 * Las claves están agrupadas por pantalla. Los textos que dependen de un dato
 * (cantidades, nombres) son funciones: `TEXTS.catalog.propertiesFound(3)`.
 *
 * No van acá: valores que se guardan en la base (ej. servicios, estados) ni
 * las plantillas de WhatsApp por defecto (`utils/whatsapp.ts`), que el admin
 * puede editar desde el panel.
 */

const plural = (count: number, singular: string, pluralForm: string) => (count === 1 ? singular : pluralForm)

export const TEXTS = {
  brand: {
    name: 'ORIGEN',
    logoAlt: 'ORIGEN Inversiones Inmobiliarias',
    city: 'Córdoba, Argentina',
    copyright: '© 2025 ORIGEN INVERSIONES INMOBILIARIAS',
  },

  common: {
    consult: 'Consultar',
    consultByWhatsapp: 'Consultar por WhatsApp',
    talkToOrigen: 'Hablar con Origen',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    generalInquiryMessage: 'Hola ORIGEN, quiero hacer una consulta.',
    comingSoonInquiryMessage: (tipoPlural: string) => `Hola ORIGEN, quiero que me avisen cuando tengan ${tipoPlural} disponibles.`,
    all: 'Todos',
    allFeminine: 'Todas',
    yes: 'Sí',
    no: 'No',
    emptyValue: '—',
    show: 'Mostrar ▼',
    hide: 'Ocultar ▲',
    edit: 'Editar',
    delete: 'Eliminar',
    cancel: 'Cancelar',
    saving: 'Guardando...',
    saveChanges: 'Guardar cambios',
    confirmDelete: (name: string) => `¿Eliminar "${name}"?`,
    unexpectedError: 'Ocurrió un error inesperado.',
  },

  units: {
    squareMeters: (value: number) => `${value} m²`,
    bedroomsShort: (count: number) => `${count} dorm.`,
    bathrooms: (count: number) => `${count} ${plural(count, 'baño', 'baños')}`,
    garages: (count: number) => `${count} ${plural(count, 'cochera', 'cocheras')}`,
    lots: (count: number) => `${count} lotes`,
    priceFrom: (price: string) => `Desde ${price}`,
  },

  commercialStatus: {
    available: 'Disponible',
    reserved: 'Reservado',
    inNegotiation: 'En negociación',
    sold: 'Vendido',
    rented: 'Alquilado',
  },

  /** Claves = valores de `TipoPropiedad` del sitio público. */
  propertyTypes: {
    CASA: 'Casa',
    DEPARTAMENTO: 'Departamento',
    PH: 'PH',
    LOCAL: 'Local',
    OFICINA: 'Oficina',
    CAMPO: 'Campo',
    CABAÑA: 'Cabaña',
    OTRO: 'Otro',
  } as Record<string, string>,

  listingTypes: {
    property: 'Propiedad',
    land: 'Terreno',
    project: 'Emprendimiento',
  },

  operations: {
    sale: 'Venta',
    rent: 'Alquiler',
  },

  publicationStatus: {
    draft: 'Borrador',
    published: 'Publicado',
    paused: 'Pausado',
  },

  nav: {
    home: 'Inicio',
    properties: 'Propiedades',
    lands: 'Terrenos',
    projects: 'Emprendimientos',
    about: 'Nosotros',
    contact: 'Contacto',
    mobileMenuLabel: 'Menú',
  },

  footer: {
    tagline: 'Acompañamos cada decisión inmobiliaria con información clara y una mirada orientada al largo plazo.',
    navigationTitle: 'Navegación',
    contactTitle: 'Contacto',
    cityUppercase: 'CÓRDOBA, ARGENTINA',
    adminLink: 'Admin',
  },

  cards: {
    surfaceLabel: 'Superficie',
    availableLotsLabel: 'Lotes disponibles',
    priceLabel: 'Precio',
    priceFromLabel: 'Desde',
    deliveryLabel: 'Entrega',
    viewProject: 'Ver emprendimiento',
  },

  /** Textos compartidos por los catálogos de Propiedades, Terrenos y Emprendimientos. */
  catalog: {
    eyebrow: 'Catálogo',
    searchAndFilter: 'Buscar y filtrar',
    activeFiltersSuffix: (count: number) => (count > 0 ? ` · ${count}` : ''),
    searchPlaceholder: 'Buscar...',
    locationFilterLabel: 'Ubicación',
    noResultsTitle: 'Sin resultados',
    noResultsHint: 'Probá con otros filtros.',
    comingSoonTitle: 'Próximamente',
    comingSoonHint: (tipoPlural: string) => `Estamos incorporando nuevos ${tipoPlural} al catálogo. Volvé pronto.`,
    comingSoonCta: '¿Buscás algo puntual? Escribinos',
  },

  properties: {
    title: 'Propiedades',
    subtitle: 'Propiedades seleccionadas para vivir o invertir.',
    propertyTypeFilterLabel: 'Tipo de propiedad',
    mortgageFilterLabel: 'Apto crédito',
    loading: 'Cargando propiedades...',
    resultsCount: (count: number) => `${count} ${plural(count, 'propiedad encontrada', 'propiedades encontradas')}`,
  },

  lands: {
    title: 'Terrenos',
    subtitle: 'Espacios para construir, desarrollar o invertir.',
    servicesFilterLabel: 'Servicios',
    loading: 'Cargando terrenos...',
    resultsCount: (count: number) => `${count} ${plural(count, 'terreno', 'terrenos')}`,
    whatsappInquiryMessage: 'Hola ORIGEN, busco un terreno específico. ¿Me ayudan a encontrarlo?',
    ctaTitle: '¿Buscás un terreno específico?',
    ctaText: 'Contanos qué necesitás y te acompañamos a encontrarlo.',
    ctaButton: 'Hablar con ORIGEN',
  },

  projects: {
    eyebrow: 'Desarrollo',
    title: 'Emprendimientos',
    subtitle: 'Proyectos que abren nuevas oportunidades.',
    loading: 'Cargando emprendimientos...',
    resultsCount: (count: number) => `${count} ${plural(count, 'emprendimiento', 'emprendimientos')}`,
  },

  home: {
    heroImageAlt: 'Arquitectura residencial premium Córdoba',
    heroEyebrow: 'Córdoba',
    heroTitle: 'Cada gran decisión inmobiliaria tiene un origen.',
    heroSubtitle: 'Propiedades, terrenos y emprendimientos seleccionados en Córdoba.',
    heroProjectsButton: 'Conocé nuestros proyectos',
    scrollHint: 'scroll',

    servicesEyebrow: 'Nuestros servicios',
    servicesTitle: '¿Qué estás buscando?',
    servicesSubtitle: 'Encontrá la alternativa que mejor se adapta a tu próximo proyecto.',
    serviceCards: {
      properties: {
        title: 'Propiedades',
        description: 'Casas, departamentos y propiedades seleccionadas para vivir o invertir.',
        cta: 'Ver propiedades',
      },
      lands: {
        title: 'Terrenos',
        description: 'Lotes y terrenos con potencial para construir, invertir o desarrollar.',
        cta: 'Ver terrenos',
      },
      projects: {
        title: 'Emprendimientos',
        description: 'Proyectos inmobiliarios y oportunidades de inversión desde el pozo.',
        cta: 'Ver emprendimientos',
      },
    },

    featuredProjectsEyebrow: 'Proyectos en desarrollo',
    featuredProjectsTitle: 'Proyectos para mirar hacia adelante.',
    featuredProjectsSubtitle: 'Conocé nuestros emprendimientos y descubrí nuevas oportunidades para vivir o invertir.',
    featuredProjectsButton: 'Ver todos los emprendimientos',

    liveOrInvestTitle: 'Una propiedad puede ser mucho más que una propiedad.',
    liveCard: {
      title: 'Para vivir',
      description: 'Encontrá un lugar que acompañe la vida que querés construir.',
      cta: 'Encontrar mi propiedad',
    },
    investCard: {
      title: 'Para invertir',
      description: 'Analizá oportunidades inmobiliarias pensadas para construir patrimonio.',
      cta: 'Ver oportunidades',
    },

    specialtyEyebrow: 'Nuestra especialidad',
    specialtyTitle: 'Conocemos dónde empieza el crecimiento.',
    specialtyText: 'Trabajamos principalmente en Córdoba Sur, acompañando a quienes buscan comprar, vender o invertir en una de las zonas de mayor desarrollo de la ciudad.',
    focusZones: ['MANANTIALES', 'BARRIO JARDÍN', 'JARDINES DEL JOCKEY', 'CAMINO SAN CARLOS'],
    focusZoneImageAlt: 'Córdoba Sur zona residencial',
    focusZoneLabel: 'Zona de foco',
    focusZoneName: 'Córdoba Sur',

    featuredPropertiesEyebrow: 'Destacadas',
    featuredPropertiesTitle: 'Propiedades seleccionadas',
    featuredPropertiesButton: 'Ver todas las propiedades',

    whyUsEyebrow: 'Por qué elegirnos',
    whyUsTitle: 'Decidir bien también es parte de la inversión.',
    whyUsSubtitle: 'Acompañamos cada operación con información clara, atención personalizada y una mirada orientada al largo plazo.',
    values: [
      { title: 'Profesionalismo', description: 'Asesoramiento serio y comprometido en cada etapa de tu operación.' },
      { title: 'Transparencia', description: 'Información clara y honesta para que tomes decisiones con confianza.' },
      { title: 'Confianza', description: 'Construida operación a operación, con personas que vuelven.' },
      { title: 'Claridad', description: 'Sin tecnicismos innecesarios. Directo al punto que importa.' },
    ],

    aboutEyebrow: 'Quiénes somos',
    aboutTitle: 'El origen de una buena decisión.',
    aboutParagraph1: 'En ORIGEN creemos que cada operación inmobiliaria comienza mucho antes de una firma. Comienza con una decisión, una necesidad o un proyecto.',
    aboutParagraph2: 'Nuestro objetivo es acompañarte con información, conocimiento y una mirada clara sobre cada oportunidad.',
    aboutButton: 'Conocer más sobre Origen',

    finalCtaImageAlt: 'Arquitectura premium',
    finalCtaTitle: 'Todo proyecto tiene un origen.',
    finalCtaSubtitle: 'Encontrá el tuyo.',
  },

  contact: {
    eyebrow: 'Quiénes somos / Contacto',
    title: 'El origen de una buena decisión.',
    intro: 'En ORIGEN creemos que cada operación inmobiliaria comienza mucho antes de una firma. Comienza con una decisión, una necesidad o un proyecto.',
    aboutTitle: 'Nuestro objetivo es acompañarte.',
    aboutParagraph1: 'En ORIGEN creemos que cada operación inmobiliaria comienza mucho antes de una firma. Comienza con una decisión, una necesidad o un proyecto.',
    aboutParagraph2: 'Nuestro objetivo es acompañarte con información, conocimiento y una mirada clara sobre cada oportunidad. Trabajamos principalmente en Córdoba Sur, la zona de mayor crecimiento de la ciudad.',
    values: [
      { title: 'Profesionalismo', description: 'Asesoramiento comprometido en cada etapa.' },
      { title: 'Transparencia', description: 'Información clara para decisiones confiadas.' },
      { title: 'Confianza', description: 'Construida operación a operación.' },
      { title: 'Claridad', description: 'Sin tecnicismos. Directo al punto.' },
    ],
    howToReachUs: 'Cómo contactarnos',
    whatsappLink: 'Hablar por WhatsApp',
  },

  detail: {
    loading: 'Cargando publicación...',
    loadError: 'No se pudo cargar la publicación.',
    backToProperties: 'Propiedades',
    backToLands: 'Terrenos',
    backToProjects: 'Emprendimientos',
    listingTypeNameProperty: 'propiedad',
    listingTypeNameLand: 'terreno',
    listingTypeNameProject: 'emprendimiento',
    notAvailableTitle: (listingTypeName: string) => `Este ${listingTypeName} ya no se encuentra disponible.`,
    notAvailableSuggestion: 'Quizás te interese alguna de estas opciones.',

    descriptionSection: 'Descripción',
    characteristicsSection: 'Características',
    servicesSection: 'Servicios',
    availableLotsSection: 'Lotes disponibles',
    typologiesSection: 'Tipologías disponibles',
    financingSection: 'Financiación',
    locationSection: 'Ubicación',

    characteristicType: 'Tipo',
    characteristicSurface: 'Superficie',
    characteristicRooms: 'Ambientes',
    characteristicBedrooms: 'Dormitorios',
    characteristicBathrooms: 'Baños',
    characteristicGarages: 'Cocheras',
    characteristicMortgage: 'Apto crédito',
    characteristicDelivery: 'Entrega',

    lotWhatsappMessage: (lotName: string, listingTitle: string) => `Hola, quisiera consultar por el ${lotName} de ${listingTitle}.`,
    typologyWhatsappMessage: (typologyName: string, listingTitle: string) => `Hola, quisiera consultar por la tipología ${typologyName} de ${listingTitle}.`,
    mapTitle: 'Mapa de ubicación',
    openInGoogleMaps: 'Abrir en Google Maps →',
    priceLabel: 'Precio',
    viewOnZonaprop: 'Ver en ZonaProp →',

    relatedEyebrow: 'También puede interesarte',
    relatedTitleProperties: 'Más propiedades',
    relatedTitleLands: 'Más terrenos',
    relatedTitleProjects: 'Otros emprendimientos',
  },

  listingsData: {
    loadError: 'No se pudieron cargar las publicaciones.',
    financingAvailableFallback: 'Financiación disponible',
  },

  auth: {
    supabaseNotConfiguredLong: 'Supabase todavía no está configurado. Copiá .env.example a .env y agregá las credenciales del proyecto.',
    supabaseNotConfiguredShort: 'Supabase todavía no está configurado.',
  },

  admin: {
    login: {
      homeButton: '⌂ Home',
      homeButtonTooltip: 'Volver al inicio',
      eyebrow: 'Área privada',
      title: 'Ingresar al Admin',
      subtitle: 'Acceso exclusivo para administrar las publicaciones de ORIGEN.',
      emailLabel: 'Email',
      passwordLabel: 'Contraseña',
      submitButton: 'Ingresar',
      submittingButton: 'Ingresando...',
    },

    loadingSession: 'Cargando sesión...',

    shell: {
      expandMenu: 'Expandir menú',
      collapseMenu: 'Colapsar menú',
      sectionGroupGeneral: 'General',
      sectionGroupContent: 'Contenido',
      sectionGroupSettings: 'Configuración',
      dashboard: 'Dashboard',
      publications: 'Publicaciones',
      whatsapp: 'WhatsApp',
      signOut: 'Cerrar sesión',
      viewSite: 'Ver sitio',
      viewSiteWithArrow: '← Ver sitio',
      breadcrumbRoot: 'Admin',
      homeButton: '⌂ Home',
      homeButtonTooltip: 'Salir del panel y volver al inicio',
    },

    whatsappSettings: {
      title: 'Configuración de WhatsApp',
      subtitle: 'Configurá el número y las plantillas de los CTAs.',
      savedNotice: 'Guardado',
      numberLabel: 'WhatsApp comercial',
      numberRequired: 'Ingresá el número de WhatsApp comercial.',
      instagramLabel: 'Instagram (URL del perfil)',
      instagramPlaceholder: 'https://instagram.com/origeninversiones',
      instagramHint: (handle: string) => `Se muestra en el footer y en Contacto como ${handle}.`,
      instagramUrlInvalid: 'Ingresá la URL completa del perfil de Instagram (https://instagram.com/usuario).',
      saveError: 'No se pudo guardar la configuración.',
      projectTemplateLabel: 'Emprendimientos',
      propertyTemplateLabel: 'Propiedades',
      landTemplateLabel: 'Terrenos',
      templateHint: 'Usá {nombre} para insertar el nombre automáticamente.',
      previewTitle: 'Previsualización',
      openTestWhatsapp: 'Abrir WhatsApp de prueba',
      sampleProjectName: 'Origen Park',
      samplePropertyName: 'Casa en Manantiales',
      sampleLandName: 'Lote en Jardines del Jockey',
    },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Resumen del catálogo conectado a Supabase. Tocá una métrica para ver esas publicaciones filtradas.',
      loading: 'Cargando métricas...',
      loadError: 'No se pudieron cargar las métricas.',
      metricTotal: 'Total',
      metricPublished: 'Publicadas',
      metricDrafts: 'Borradores',
      metricProperties: 'Propiedades',
      metricLands: 'Terrenos',
      metricProjects: 'Emprendimientos',
      noteListings: 'publicaciones',
      noteVisible: 'visibles',
      notePending: 'pendientes',
      noteInCatalog: 'en catálogo',
    },

    publications: {
      title: 'Publicaciones',
      subtitle: 'Alta, edición y publicación del catálogo real.',
      newButton: 'Nueva publicación',
      newCollapsedButton: '+ Nueva publicación',
      editTitle: 'Editar publicación',
      newTitle: 'Nueva publicación',
      previewButton: 'Previsualizar',
      viewOnSiteButton: 'Ver en el sitio',
      publishButton: 'Publicar',
      pauseButton: 'Pausar',
      createButton: 'Crear publicación',
      applyChangesButton: 'Aplicar cambios',
      hasTypologiesCheckbox: 'Esta publicación tiene unidades / tipologías',
      saveBeforeImagesHint: 'Guardá la publicación primero para poder cargar sus imágenes.',

      fields: {
        title: 'Título',
        titleHint: 'Letras, números y espacios. Genera la URL pública.',
        type: 'Tipo',
        typeHint: 'Define en qué catálogo público aparece.',
        description: 'Descripción',
        descriptionHint: 'Texto libre, sin límite de longitud.',
        operation: 'Operación',
        operationHint: 'Venta o alquiler.',
        publicationStatus: 'Estado de publicación',
        publicationStatusHint: 'Borrador y Pausado no se ven en el sitio público.',
        commercialStatus: 'Estado comercial',
        commercialStatusHint: '"Vendido" oculta la publicación aunque esté Publicado.',
        price: 'Precio',
        priceHint: 'Número entero o decimal, sin puntos ni comas de miles. Ej: 150000.',
        currency: 'Moneda',
        currencyHint: '3 o 4 letras. Ej: USD, ARS.',
        priceFrom: 'Mostrar precio desde',
        priceFromHint: 'Antepone "Desde" al precio en la ficha pública.',
        city: 'Ciudad',
        cityHint: 'Texto libre. Obligatorio.',
        neighborhood: 'Barrio',
        neighborhoodHint: 'Texto libre, opcional.',
        address: 'Dirección',
        addressHint: 'Texto libre, opcional.',
        latitude: 'Latitud',
        latitudeHint: 'Decimal entre -90 y 90. Ej: -31.4201.',
        longitude: 'Longitud',
        longitudeHint: 'Decimal entre -180 y 180. Ej: -64.1888.',
        deliveryDate: 'Entrega',
        deliveryDateHint: 'Fecha estimada, sobre todo para emprendimientos.',
        financing: 'Financiación disponible',
        financingHint: 'Marca general; el texto va en "Detalle de financiación".',
        surface: 'Superficie m²',
        surfaceHint: 'Número en metros cuadrados. Ej: 120.',
        propertyType: 'Tipo de propiedad',
        propertyTypeUnspecified: 'Sin especificar',
        propertyTypeHint: 'Solo se usa para publicaciones de tipo Propiedad.',
        rooms: 'Ambientes',
        roomsHint: 'Cantidad total de ambientes.',
        bedrooms: 'Dormitorios',
        bedroomsHint: 'Cantidad de dormitorios.',
        bathrooms: 'Baños',
        bathroomsHint: 'Cantidad de baños.',
        garages: 'Cocheras',
        garagesHint: 'Cantidad de cocheras.',
        mortgageEligible: 'Apto crédito',
        mortgageEligibleHint: 'Indica si acepta crédito hipotecario.',
        financingDetails: 'Detalle de financiación',
        financingDetailsPlaceholder: 'Ej: crédito hipotecario UVA, 30% anticipo + 24 cuotas...',
        financingDetailsHint: 'Texto libre. Aparece en la ficha pública si tiene contenido.',
        services: 'Servicios',
        servicesHint: 'Elegí los que apliquen; ninguno es obligatorio.',
      },

      validation: {
        titleRequired: 'El título es obligatorio.',
        titleNeedsLetterOrNumber: 'El título debe incluir al menos una letra o número (se usa para generar la URL pública).',
        cityRequired: 'La ciudad es obligatoria.',
        priceNegative: 'El precio no puede ser negativo.',
        currencyLength: 'La moneda debe tener 3 o 4 caracteres (ej. USD).',
        priceFromWithoutPrice: 'Marcaste "Mostrar precio desde" pero no cargaste un precio.',
        coordinatesTogether: 'Cargá latitud y longitud juntas, o dejá las dos vacías.',
        latitudeRange: 'La latitud debe estar entre -90 y 90.',
        longitudeRange: 'La longitud debe estar entre -180 y 180.',
        surfaceNegative: 'La superficie no puede ser negativa.',
        bedroomsNegative: 'Los dormitorios no pueden ser negativos.',
        bathroomsNegative: 'Los baños no pueden ser negativos.',
        garagesNegative: 'Las cocheras no pueden ser negativas.',
        roomsNegative: 'Los ambientes no pueden ser negativos.',
      },

      notices: {
        updated: 'Publicación actualizada.',
        created: 'Publicación creada.',
        deleted: 'Publicación eliminada.',
        statusUpdated: 'Estado actualizado.',
      },

      errors: {
        previewLoad: 'No se pudo cargar la previsualización.',
        listLoad: 'No se pudieron cargar las publicaciones.',
        save: 'No se pudo guardar la publicación.',
        delete: 'No se pudo eliminar la publicación.',
        statusUpdate: 'No se pudo actualizar el estado.',
      },

      filters: {
        title: 'Filtros',
        activeCountSuffix: (count: number) => (count > 0 ? ` · ${count} ${plural(count, 'activo', 'activos')}` : ''),
        search: 'Buscar',
        searchPlaceholder: 'Buscar en todos los campos...',
        type: 'Tipo',
        operation: 'Operación',
        publicationStatus: 'Estado de publicación',
        commercialStatus: 'Estado comercial',
        city: 'Ciudad',
        neighborhood: 'Barrio',
        propertyType: 'Tipo de propiedad',
        service: 'Servicio',
        priceFrom: 'Precio "desde"',
        financing: 'Financiación',
        mortgageEligible: 'Apto crédito',
        clearButton: 'Limpiar filtros',
      },

      resultsCount: (shown: number, total: number) => `${shown} de ${total} publicaciones`,
      loading: 'Cargando publicaciones...',
      noLocation: 'Sin ubicación',
      noMatches: 'Ninguna publicación coincide con los filtros.',
      emptyCatalog: 'No hay publicaciones todavía.',

      previewDialogLabel: 'Previsualización de publicación',
      previewHeader: (status: string) => `Previsualización · ${status}`,
      closePreview: 'Cerrar previsualización',
    },

    typologies: {
      title: 'Unidades / Tipologías',
      nameLabel: 'Nombre',
      nameHint: 'Ej: "2 ambientes", "Lote 12".',
      surfaceLabel: 'Superficie m²',
      surfaceHint: 'Número en metros cuadrados.',
      bedroomsLabel: 'Dormitorios',
      bedroomsHint: 'Cantidad de dormitorios.',
      bathroomsLabel: 'Baños',
      bathroomsHint: 'Cantidad de baños.',
      priceLabel: 'Precio',
      priceHint: 'Número entero o decimal, sin separadores de miles.',
      currencyLabel: 'Moneda',
      currencyHint: '3 o 4 letras. Ej: USD, ARS.',
      descriptionLabel: 'Descripción',
      descriptionHint: 'Texto libre, opcional.',
      addButton: 'Agregar unidad',
      loading: 'Cargando unidades…',
      empty: 'Todavía no hay unidades cargadas.',
      nameRequired: 'El nombre es obligatorio.',
      loadError: 'No se pudieron cargar las unidades.',
      saveError: 'No se pudo guardar la unidad.',
      deleteError: 'No se pudo eliminar la unidad.',
    },

    images: {
      title: 'Imágenes',
      instructions: 'La primera imagen es la portada. JPG, PNG o WebP; hasta 10 MB por archivo.',
      addButton: 'Agregar imágenes',
      uploading: 'Subiendo…',
      loading: 'Cargando imágenes…',
      empty: 'Todavía no hay imágenes. Guardá la publicación y cargalas desde aquí.',
      coverBadge: 'Portada',
      coverAlt: 'Portada de la publicación',
      imageAlt: (position: number) => `Imagen ${position} de la publicación`,
      confirmDelete: '¿Eliminar esta imagen?',
      invalidFileType: 'Elegí una imagen JPG, PNG o WebP.',
      fileTooLarge: 'La imagen no puede superar los 10 MB.',
      bucketMissing: 'No existe el bucket "listing-images" en Supabase. Ejecutá la migración 20260921004000_create_listing_images_bucket.sql en el SQL Editor.',
      loadError: 'No se pudieron cargar las imágenes.',
      uploadError: 'No se pudo subir la imagen.',
      reorderError: 'No se pudo actualizar el orden.',
      deleteError: 'No se pudo eliminar la imagen.',
    },
  },
}
